-- MySQL Script generated by MySQL Workbench
-- Fri 17 Mar 2017 06:35:06 PM CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mensarium_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mensarium_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mensarium_db` DEFAULT CHARACTER SET utf8 ;
USE `mensarium_db` ;

-- -----------------------------------------------------
-- Table `mensarium_db`.`TipNaloga`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mensarium_db`.`TipNaloga` ;

CREATE TABLE IF NOT EXISTS `mensarium_db`.`TipNaloga` (
  `idTip` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTip`),
  UNIQUE INDEX `naziv_UNIQUE` (`naziv` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mensarium_db`.`Fakulteti`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mensarium_db`.`Fakulteti` ;

CREATE TABLE IF NOT EXISTS `mensarium_db`.`Fakulteti` (
  `idFakultet` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idFakultet`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mensarium_db`.`Korisnici`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mensarium_db`.`Korisnici` ;

CREATE TABLE IF NOT EXISTS `mensarium_db`.`Korisnici` (
  `idKorisnik` INT NOT NULL AUTO_INCREMENT,
  `korisnickoIme` VARCHAR(20) NULL,
  `email` VARCHAR(45) NULL,
  `lozinka` VARCHAR(128) NOT NULL,
  `ime` VARCHAR(20) NOT NULL,
  `prezime` VARCHAR(20) NOT NULL,
  `datumRodjenja` DATE NOT NULL,
  `datumRegistracije` INT NOT NULL,
  `brojTelefona` VARCHAR(20) NULL,
  `fakultet` INT NULL,
  `brojIndeksa` VARCHAR(10) NULL,
  `datumVaziDo` DATE NULL,
  `tipNaloga` INT NOT NULL,
  PRIMARY KEY (`idKorisnik`),
  UNIQUE INDEX `KORISNICKO_IME_UNIQUE` (`korisnickoIme` ASC),
  UNIQUE INDEX `E-MAIL_UNIQUE` (`email` ASC),
  INDEX `fk_tb_Korisnici_tb_TipNaloga_idx` (`tipNaloga` ASC),
  INDEX `fk_tb_Korisnici_tb_Fakulteti1_idx` (`fakultet` ASC),
  CONSTRAINT `fk_tb_Korisnici_tb_TipNaloga`
    FOREIGN KEY (`tipNaloga`)
    REFERENCES `mensarium_db`.`TipNaloga` (`idTip`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_Korisnici_tb_Fakulteti1`
    FOREIGN KEY (`fakultet`)
    REFERENCES `mensarium_db`.`Fakulteti` (`idFakultet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mensarium_db`.`TipObroka`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mensarium_db`.`TipObroka` ;

CREATE TABLE IF NOT EXISTS `mensarium_db`.`TipObroka` (
  `idTipObroka` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idTipObroka`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mensarium_db`.`Menze`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mensarium_db`.`Menze` ;

CREATE TABLE IF NOT EXISTS `mensarium_db`.`Menze` (
  `idMenza` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(45) NOT NULL,
  `lokacija` VARCHAR(45) NOT NULL,
  `radnoVreme` VARCHAR(45) NULL,
  `vanrednoNeRadi` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`idMenza`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mensarium_db`.`Obroci`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mensarium_db`.`Obroci` ;

CREATE TABLE IF NOT EXISTS `mensarium_db`.`Obroci` (
  `idObrok` BIGINT NOT NULL,
  `tipObroka` INT NOT NULL,
  `idUplatioca` INT NOT NULL,
  `iskoriscen` TINYINT(1) NULL DEFAULT 0,
  `datumUplacivanja` DATETIME NOT NULL,
  `datumIskoriscenja` VARCHAR(45) NULL,
  `lokacijaUplate` INT NOT NULL,
  `lokacijaIskoriscenja` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idObrok`),
  INDEX `fk_tb_obroci_tb_TipObroka1_idx` (`tipObroka` ASC),
  INDEX `fk_tb_obroci_tb_Korisnici1_idx` (`idUplatioca` ASC),
  INDEX `fk_tb_Obroci_tb_Menze1_idx` (`lokacijaUplate` ASC),
  INDEX `fk_tb_Obroci_tb_Menze2_idx` (`lokacijaIskoriscenja` ASC),
  CONSTRAINT `fk_tb_obroci_tb_TipObroka1`
    FOREIGN KEY (`tipObroka`)
    REFERENCES `mensarium_db`.`TipObroka` (`idTipObroka`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_obroci_tb_Korisnici1`
    FOREIGN KEY (`idUplatioca`)
    REFERENCES `mensarium_db`.`Korisnici` (`idKorisnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_Obroci_tb_Menze1`
    FOREIGN KEY (`lokacijaUplate`)
    REFERENCES `mensarium_db`.`Menze` (`idMenza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_Obroci_tb_Menze2`
    FOREIGN KEY (`lokacijaIskoriscenja`)
    REFERENCES `mensarium_db`.`Menze` (`idMenza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mensarium_db`.`Pracenja`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mensarium_db`.`Pracenja` ;

CREATE TABLE IF NOT EXISTS `mensarium_db`.`Pracenja` (
  `idPratilac` INT NOT NULL,
  `idPraceni` INT NOT NULL,
  PRIMARY KEY (`idPratilac`, `idPraceni`),
  INDEX `fk_tb_Korisnici_has_tb_Korisnici_tb_Korisnici2_idx` (`idPraceni` ASC),
  INDEX `fk_tb_Korisnici_has_tb_Korisnici_tb_Korisnici1_idx` (`idPratilac` ASC),
  CONSTRAINT `fk_tb_Korisnici_has_tb_Korisnici_tb_Korisnici1`
    FOREIGN KEY (`idPratilac`)
    REFERENCES `mensarium_db`.`Korisnici` (`idKorisnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_Korisnici_has_tb_Korisnici_tb_Korisnici2`
    FOREIGN KEY (`idPraceni`)
    REFERENCES `mensarium_db`.`Korisnici` (`idKorisnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mensarium_db`.`Objave`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mensarium_db`.`Objave` ;

CREATE TABLE IF NOT EXISTS `mensarium_db`.`Objave` (
  `idKorisnika` INT NOT NULL AUTO_INCREMENT,
  `idLokacija` INT NOT NULL,
  `datumObjave` DATETIME NULL,
  `textObjave` VARCHAR(45) NULL,
  PRIMARY KEY (`idKorisnika`),
  INDEX `fk_tb_Objave_tb_Menze1_idx` (`idLokacija` ASC),
  CONSTRAINT `fk_tb_Objave_tb_Korisnici1`
    FOREIGN KEY (`idKorisnika`)
    REFERENCES `mensarium_db`.`Korisnici` (`idKorisnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_Objave_tb_Menze1`
    FOREIGN KEY (`idLokacija`)
    REFERENCES `mensarium_db`.`Menze` (`idMenza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mensarium_db`.`Pozivanja`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mensarium_db`.`Pozivanja` ;

CREATE TABLE IF NOT EXISTS `mensarium_db`.`Pozivanja` (
  `idPoziva` INT NOT NULL AUTO_INCREMENT,
  `idPozivaoca` INT NOT NULL,
  `datumPoziva` DATETIME NOT NULL,
  `vremeTrajanja` TIME NULL,
  PRIMARY KEY (`idPoziva`),
  INDEX `fk_tb_Pozivanja_tb_Korisnici1_idx` (`idPozivaoca` ASC),
  CONSTRAINT `fk_tb_Pozivanja_tb_Korisnici1`
    FOREIGN KEY (`idPozivaoca`)
    REFERENCES `mensarium_db`.`Korisnici` (`idKorisnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mensarium_db`.`PozivanjaPozvani`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mensarium_db`.`PozivanjaPozvani` ;

CREATE TABLE IF NOT EXISTS `mensarium_db`.`PozivanjaPozvani` (
  `idPoziva` INT NOT NULL,
  `idPozvanog` INT NOT NULL,
  `odgovorPozvanog` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`idPoziva`, `idPozvanog`),
  INDEX `fk_tb_PozivanjaPozvani_tb_Korisnici1_idx` (`idPozvanog` ASC),
  CONSTRAINT `fk_tb_PozivanjaPozvani_tb_Pozivanja1`
    FOREIGN KEY (`idPoziva`)
    REFERENCES `mensarium_db`.`Pozivanja` (`idPoziva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_PozivanjaPozvani_tb_Korisnici1`
    FOREIGN KEY (`idPozvanog`)
    REFERENCES `mensarium_db`.`Korisnici` (`idKorisnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mensarium_db`.`TipNaloga`
-- -----------------------------------------------------
START TRANSACTION;
USE `mensarium_db`;
INSERT INTO `mensarium_db`.`TipNaloga` (`idTip`, `naziv`) VALUES (1, 'Administrator');
INSERT INTO `mensarium_db`.`TipNaloga` (`idTip`, `naziv`) VALUES (2, 'Menadžer');
INSERT INTO `mensarium_db`.`TipNaloga` (`idTip`, `naziv`) VALUES (3, 'Uplata');
INSERT INTO `mensarium_db`.`TipNaloga` (`idTip`, `naziv`) VALUES (4, 'Naplata');
INSERT INTO `mensarium_db`.`TipNaloga` (`idTip`, `naziv`) VALUES (5, 'Korisnik');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mensarium_db`.`TipObroka`
-- -----------------------------------------------------
START TRANSACTION;
USE `mensarium_db`;
INSERT INTO `mensarium_db`.`TipObroka` (`idTipObroka`, `naziv`) VALUES (1, 'Doručak');
INSERT INTO `mensarium_db`.`TipObroka` (`idTipObroka`, `naziv`) VALUES (2, 'Ručak');
INSERT INTO `mensarium_db`.`TipObroka` (`idTipObroka`, `naziv`) VALUES (3, 'Večera');

COMMIT;

